import runner_Ambulances
import runner_ATO
import runner_newsvendor_deterministic
import runner_newsvendor_known_noisy
import runner_newsvendor_unknown_noisy
import runner_synthetic2d
import runner_toyfun
